### ISSUE TITLE
License not specified

### ISSUE THREAD

**Issue by u-235** [sokunmin/stl-gcode-viewer#5]
Hi.  
I like your project and would like to use it, but it is not possible without a license. Could you please specify the license?

**Comment by sokunmin** [comment]
Hi,
Thank you. I'm glad it is useful to you. 

I modified from the Qt official example directly. The example was [under LGPL](http://man.hubwiz.com/docset/Qt_5.docset/Contents/Resources/Documents/doc.qt.io/qt-5/qtwidgets-graphicsview-boxes-trackball-cpp.html) while it is [under BSD](https://doc.qt.io/qt-6/examples-license.html) nowadays. Besides, [gcode](https://github.com/sokunmin/stl-gcode-viewer/blob/856210d7e627c804f49e514edaec85508e01a6f1/gcode/gcode.cpp) is under GPL.  

It seems complicated. My initial intention is to let everyone use it freely, but I'm not sure whether I can change to MIT or just derive the license (LGPL/BSD/GPL). 

If you are familiar with this, please let me know. I can create a proper license for open source community.

**Comment by u-235** [comment]
As far as I know, if a project uses GPL-licensed components, the whole project must be GPL-compatible. And it is probably easier to choose GPLv3.

There is one more difficulty. Will this be considered a change of license? If so, you'll need to get permission from @Depau.

**Comment by sokunmin** [comment]
So it seems that GPLv3 is the only option to be created.

@Depau contributed a bug fix (See [PR](https://github.com/sokunmin/stl-gcode-viewer/pull/4/files)). Still require his permission? 
If so, does it need to get every contributor's permission if it's a large open source project?

**Comment by u-235** [comment]
> @Depau contributed a bug fix (See [PR](https://github.com/sokunmin/stl-gcode-viewer/pull/4/files)). Still require his permission?

I can't say for sure if you need Depau's permission or not. In my opinion, it's better to be on the safe side and get Depau's approval. It makes sense that Depau brought his code under one license (thereby agreeing with it) and may be against using that code under another license.

**Comment by depau** [comment]
Hi,
Sorry for the late reply, GPLv3 works for me!

**Comment by sokunmin** [comment]
@Depau Thank you for the reply.

@u-235 I've created the license and updated the README.md. Please have a look (hope I made it right.)

**Comment by u-235** [comment]
This looks fine, but there is one nuance: [GNU recommends][1] that a copyright notice and a license notice be placed at the beginning of each source file.

[1]: https://www.gnu.org/licenses/gpl-howto.en.html

**Comment by sokunmin** [comment]
I'm confused about copyright. Does it belong to Qt or me since I modified from Qt example?

**Comment by sokunmin** [comment]
Notice added.
